on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: bkimminich/juice-shop
      options: "--entrypoint /bin/bash"
    steps:
         - name: Log the step container node version
           uses: docker://bkimminich/juice-shop
           with:
             entrypoint: /bin/echo
             args: -v


