on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: bkimminich/juice-shop
    steps:
         - name: Log the step container node version
           uses: docker://bkimminich/juice-shop
           with:
             entrypoint: usr/local/bin/echo
             args: -v
         - name: Step with docker to echo a string
           uses: docker://bkimminich/juice-shop
           with:
             entrypoint: /bin/echo
             args: Hello Docker !


