on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: dcmjid/juice-shop
    steps:
         - name: Log the parent container node version
           run: |
             node -v 
           # Echo the node version of the parent container


         - name: Log the step container node version
           uses: docker://dcmjid/juice-shop
           with:
             entrypoint: usr/local/bin/echo
             args: -v
            # Echo the node version of this step container based on this 12.14.1-alpine3.10 image


         - name: Step with docker to echo a string
           uses: docker://dcmjid/juice-shop
           with:
             entrypoint: /bin/echo
             args: Hello Docker !


